"""Dodao cenu u porudzbinuprodukt

Revision ID: 8eb85a60b488
Revises: 5c82c6687bff
Create Date: 2022-08-11 08:11:25.012312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb85a60b488'
down_revision = '5c82c6687bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productorders', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productorders', 'price')
    # ### end Alembic commands ###
