"""Dodajem date u ProductOrder i ostalo do zavrsetka u ordere

Revision ID: edc782e2027f
Revises: 8eb85a60b488
Create Date: 2022-08-11 08:45:53.743070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc782e2027f'
down_revision = '8eb85a60b488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('leftToComplete', sa.Integer(), nullable=True))
    op.add_column('productorders', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productorders', 'date')
    op.drop_column('orders', 'leftToComplete')
    # ### end Alembic commands ###
