version: '3'

services:
  appDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
  adminerApp:
    image: adminer
    ports:
      - 8082:8080
  redis:
    image: redis
    ports:
      - 6379:6379
